# Generated by Django 3.0.6 on 2020-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='timeMinutes',
            new_name='time_minutes',
        ),
    ]
